function state = temperature_model(temperature_C,torque_Nm,p)
%TEMPERATURE_MODEL Temperature-induced sensitivity and compensation model.
% Chain: T -> G(T) and P(T) -> torsional/phase sensitivity -> phase error
% -> compensation OFF/ON. Temperature must be scalar; torque may be a vector.
if nargin<3||isempty(p), p=temperature_parameter(); end
validateattributes(temperature_C,{'numeric'},{'scalar','real','finite'},mfilename,'temperature_C');
validateattributes(torque_Nm,{'numeric'},{'vector','real','finite'},mfilename,'torque_Nm');
assert(strcmp(p.metadata.parameter_source,'simulation/default')&& ...
    ~p.metadata.coefficients_verified,'temperature_model:Source', ...
    'Unverified coefficients must remain marked simulation/default.');

temperature_C=double(temperature_C); torque_Nm=double(torque_Nm(:));
dT=temperature_C-p.reference_temperature_C;
G0=p.material.shear_modulus_ref_Pa;
alpha_G=p.material.shear_modulus_temp_coefficient_per_C;
P0=p.grating.period_ref_m;
alpha_P=p.grating.period_temp_coefficient_per_C;
GT=G0*(1+alpha_G*dT);
PT=P0*(1+alpha_P*dT);
assert(GT>0&&PT>0,'temperature_model:Range','Temperature-adjusted G and P must remain positive.');

common=struct('torsion_length',p.mechanics.torsion_length_m, ...
    'shaft_diameter',p.mechanics.shaft_diameter_m, ...
    'grating_radius',p.mechanics.grating_radius_m,'phase_zero',0, ...
    'parameter_source',p.metadata.parameter_source);
reference_parameter=common; reference_parameter.shear_modulus=G0; reference_parameter.grating_period=P0;
actual_parameter=common; actual_parameter.shear_modulus=GT; actual_parameter.grating_period=PT;
reference=torque_model(torque_Nm,reference_parameter);
actual=torque_model(torque_Nm,actual_parameter);

J=actual.polar_moment;
theta_sensitivity_ref=p.mechanics.torsion_length_m/(G0*J);
theta_sensitivity_T=p.mechanics.torsion_length_m/(GT*J);
displacement_sensitivity_ref=p.mechanics.grating_radius_m*theta_sensitivity_ref;
displacement_sensitivity_T=p.mechanics.grating_radius_m*theta_sensitivity_T;
phase_sensitivity_ref=2*pi*displacement_sensitivity_ref/P0;
phase_sensitivity_T=2*pi*displacement_sensitivity_T/PT;

phase_measured=actual.optical_phase;
torque_off=phase_measured/phase_sensitivity_ref;
displacement_off=phase_measured*P0/(2*pi);
torque_on=phase_measured/phase_sensitivity_T;
displacement_on=phase_measured*PT/(2*pi);

off=struct('torque_estimate',torque_off,'torque_error',torque_off-torque_Nm, ...
    'displacement_estimate',displacement_off, ...
    'displacement_error',displacement_off-actual.relative_displacement);
on=struct('torque_estimate',torque_on,'torque_error',torque_on-torque_Nm, ...
    'displacement_estimate',displacement_on, ...
    'displacement_error',displacement_on-actual.relative_displacement);
state=struct('temperature_C',temperature_C,'delta_temperature_C',dT, ...
    'torque_true',torque_Nm,'shear_modulus_Pa',GT,'grating_period_m',PT, ...
    'polar_moment_m4',J,'torsional_sensitivity_rad_per_Nm',theta_sensitivity_T, ...
    'torsional_sensitivity_variation',(theta_sensitivity_T/theta_sensitivity_ref)-1, ...
    'displacement_sensitivity_m_per_Nm',displacement_sensitivity_T, ...
    'phase_sensitivity_rad_per_Nm',phase_sensitivity_T, ...
    'true_torsion_angle',actual.torsion_angle, ...
    'true_displacement',actual.relative_displacement, ...
    'measured_phase',phase_measured,'reference_phase',reference.optical_phase, ...
    'phase_error',phase_measured-reference.optical_phase, ...
    'compensation_off',off,'compensation_on',on, ...
    'parameter',p,'parameter_source',p.metadata.parameter_source);
end
