function acceptance = stage15_acceptance()
%STAGE15_ACCEPTANCE Verify temperature physics and compensation paths.
root=fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root,'config'),fullfile(root,'mechanics'),fullfile(root,'experiment'));
p=temperature_parameter(); torque=[-8 -1 0 1 8].';
s_ref=temperature_model(p.reference_temperature_C,torque,p);
s_low=temperature_model(min(p.temperature_C),torque,p);
s_high=temperature_model(max(p.temperature_C),torque,p);
tol=1e-12;
acceptance=struct();
acceptance.pass_source=strcmp(p.metadata.parameter_source,'simulation/default')&& ...
    ~p.metadata.coefficients_verified&&strcmp(s_ref.parameter_source,'simulation/default');
acceptance.pass_reference=abs(s_ref.shear_modulus_Pa-p.material.shear_modulus_ref_Pa)<tol&& ...
    max(abs(s_ref.phase_error))<tol&&max(abs(s_ref.compensation_off.torque_error))<tol&& ...
    max(abs(s_ref.compensation_on.torque_error))<tol;
acceptance.pass_material_variation=s_high.shear_modulus_Pa<s_ref.shear_modulus_Pa&& ...
    s_low.shear_modulus_Pa>s_ref.shear_modulus_Pa;
acceptance.pass_sensitivity_variation=s_high.torsional_sensitivity_rad_per_Nm> ...
    s_ref.torsional_sensitivity_rad_per_Nm&&s_low.torsional_sensitivity_rad_per_Nm< ...
    s_ref.torsional_sensitivity_rad_per_Nm;
acceptance.pass_off_error=max(abs(s_high.compensation_off.torque_error))>0&& ...
    max(abs(s_high.compensation_off.displacement_error))>0;
acceptance.pass_on_compensation=max(abs(s_high.compensation_on.torque_error))<tol&& ...
    max(abs(s_high.compensation_on.displacement_error))<tol&& ...
    max(abs(s_low.compensation_on.torque_error))<tol&& ...
    max(abs(s_low.compensation_on.displacement_error))<tol;
output_folder=fullfile(root,'data','stage15');
report=stage15_temperature_evaluation(p,output_folder);
acceptance.pass_complete=size(report.results,1)==numel(p.temperature_C)*numel(p.torque_Nm)&& ...
    all(report.results.parameter_source=="simulation/default");
acceptance.pass_comparison=all(report.summary.torque_rmse_on_Nm<=report.summary.torque_rmse_off_Nm+tol)&& ...
    all(report.summary.displacement_rmse_on_m<=report.summary.displacement_rmse_off_m+tol);
acceptance.pass_files=isfile(fullfile(output_folder,'stage15_report.md'))&& ...
    isfile(fullfile(output_folder,'stage15_report.mat'))&& ...
    isfile(fullfile(output_folder,'stage15_temperature_results.csv'))&& ...
    isfile(fullfile(output_folder,'stage15_temperature_summary.csv'))&& ...
    numel(report.figure_files)==6&&all(isfile(report.figure_files));
acceptance.temperature_count=numel(p.temperature_C);
acceptance.torque_count=numel(p.torque_Nm);
acceptance.result_row_count=size(report.results,1);
acceptance.output_folder=output_folder;
acceptance.pass=acceptance.pass_source&&acceptance.pass_reference&& ...
    acceptance.pass_material_variation&&acceptance.pass_sensitivity_variation&& ...
    acceptance.pass_off_error&&acceptance.pass_on_compensation&& ...
    acceptance.pass_complete&&acceptance.pass_comparison&&acceptance.pass_files;
assert(acceptance.pass,'stage15_acceptance:Failed','Stage 15 acceptance failed.');
end
