function acceptance = stage14_acceptance()
%STAGE14_ACCEPTANCE Verify complete, non-filtered formal comparison output.
root=fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root,'config'),fullfile(root,'model'),fullfile(root,'signal'), ...
    fullfile(root,'algorithm'),fullfile(root,'mechanics'),fullfile(root,'interface'), ...
    fullfile(root,'experiment'));
output_folder=fullfile(root,'data','stage14');
report=stage14_comparison(parameter(),output_folder);
required_cases=["ideal","amplitude_mismatch","phase_error","dc_offset", ...
    "snr_30dB","snr_20dB","snr_10dB","torque_neg8Nm","torque_neg4Nm", ...
    "torque_neg1Nm","torque_0Nm","torque_pos1Nm","torque_pos4Nm","torque_pos8Nm"];
required_methods=["Patent 1/4","Patent 1/16","Patent 1/32","Traditional atan2","Existing improved"];
actual_cases=unique(report.results.case_name,'stable');
actual_methods=unique(report.results.method,'stable');
acceptance=struct();
acceptance.pass_all_cases=isequal(actual_cases,required_cases.')&&height(report.results)==70;
acceptance.pass_all_methods=isequal(actual_methods,required_methods.');
acceptance.pass_no_dropped_failures=height(report.failures)==sum(report.results.status=="failed")&& ...
    height(report.anomalies)==sum(report.results.status~="ok");
ok=report.results.status=="ok"|report.results.status=="warning";
acceptance.pass_metrics=all(isfinite(report.results.rmse_m(ok)))&& ...
    all(isfinite(report.results.mae_m(ok)))&&all(isfinite(report.results.maximum_error_m(ok)))&& ...
    all(isfinite(report.results.resolution_m(ok)))&& ...
    all((report.results.robustness_score(ok)>=0&report.results.robustness_score(ok)<=1)| ...
    (report.results.status(ok)=="warning"&isnan(report.results.robustness_score(ok))));
ideal=report.results(report.results.case_name=="ideal",:);
step4=ideal.nominal_step_m(ideal.method=="Patent 1/4");
step16=ideal.nominal_step_m(ideal.method=="Patent 1/16");
step32=ideal.nominal_step_m(ideal.method=="Patent 1/32");
acceptance.pass_subdivision_resolution=abs(step4/step16-4)<1e-12&& ...
    abs(step16/step32-2)<1e-12;
acceptance.pass_report_files=isfile(fullfile(output_folder,'stage14_report.mat'))&& ...
    isfile(fullfile(output_folder,'stage14_results.csv'))&& ...
    isfile(fullfile(output_folder,'stage14_case_definitions.csv'))&& ...
    isfile(fullfile(output_folder,'stage14_method_summary.csv'))&& ...
    isfile(fullfile(output_folder,'stage14_report.md'));
acceptance.pass_figures=numel(report.figure_files)==6&&all(isfile(report.figure_files));
acceptance.case_count=numel(actual_cases); acceptance.method_count=numel(actual_methods);
acceptance.result_row_count=height(report.results); acceptance.failure_row_count=height(report.failures);
acceptance.warning_row_count=sum(report.results.status=="warning");
acceptance.hard_failure_row_count=sum(report.results.status=="failed");
acceptance.output_folder=output_folder;
acceptance.pass=acceptance.pass_all_cases&&acceptance.pass_all_methods&& ...
    acceptance.pass_no_dropped_failures&&acceptance.pass_metrics&& ...
    acceptance.pass_subdivision_resolution&&acceptance.pass_report_files&&acceptance.pass_figures;
assert(acceptance.pass,'stage14_acceptance:Failed','Stage 14 comparison acceptance failed.');
end
